### ISSUE TITLE
make px4_sitl gazebo fail in v1.11.2

### ISSUE THREAD

**Issue by mzahana** [PX4/PX4-Autopilot#16261]
**Describe the bug**
I am not able to compile the Gazebo SITL target on release  `v1.11.2` using
```
make px4_sitl gazebo
```

I get the following error(s)

```sh
[20/749] Generating parameters.xml
FAILED: parameters.xml parameters.json 
cd /home/arrow/Firmware/build/px4_sitl_default/src/lib/parameters && /usr/bin/python3 /home/arrow/Firmware/src/lib/parameters/px_process_params.py --src-path /home/arrow/Firmware/src/lib/airspeed /home/arrow/Firmware/src/lib/airspeed_validator /home/arrow/Firmware/src/lib/avoidance /home/arrow/Firmware/src/lib/battery /home/arrow/Firmware/src/lib/bezier /home/arrow/Firmware/src/lib/cdev /home/arrow/Firmware/src/lib/cdev/test /home/arrow/Firmware/src/lib/circuit_breaker /home/arrow/Firmware/src/lib/collision_prevention /home/arrow/Firmware/src/lib/controllib /home/arrow/Firmware/src/lib/controllib/controllib_test /home/arrow/Firmware/src/lib/conversion /home/arrow/Firmware/src/lib/drivers/accelerometer /home/arrow/Firmware/src/lib/drivers/airspeed /home/arrow/Firmware/src/lib/drivers/barometer /home/arrow/Firmware/src/lib/drivers/device /home/arrow/Firmware/src/lib/drivers/gyroscope /home/arrow/Firmware/src/lib/drivers/led /home/arrow/Firmware/src/lib/drivers/magnetometer /home/arrow/Firmware/src/lib/drivers/rangefinder /home/arrow/Firmware/src/lib/drivers/smbus /home/arrow/Firmware/src/lib/flight_tasks /home/arrow/Firmware/src/lib/flight_tasks/tasks/FlightTask /home/arrow/Firmware/src/lib/flight_tasks/tasks/Utility /home/arrow/Firmware/src/lib/flight_tasks/tasks/Auto /home/arrow/Firmware/src/lib/flight_tasks/tasks/AutoMapper /home/arrow/Firmware/src/lib/flight_tasks/tasks/ManualAltitude /home/arrow/Firmware/src/lib/flight_tasks/tasks/ManualAltitudeSmooth /home/arrow/Firmware/src/lib/flight_tasks/tasks/ManualAltitudeSmoothVel /home/arrow/Firmware/src/lib/flight_tasks/tasks/ManualPosition /home/arrow/Firmware/src/lib/flight_tasks/tasks/ManualPositionSmooth /home/arrow/Firmware/src/lib/flight_tasks/tasks/ManualPositionSmoothVel /home/arrow/Firmware/src/lib/flight_tasks/tasks/AutoLineSmoothVel /home/arrow/Firmware/src/lib/flight_tasks/tasks/AutoFollowMe /home/arrow/Firmware/src/lib/flight_tasks/tasks/Offboard /home/arrow/Firmware/src/lib/flight_tasks/tasks/Failsafe /home/arrow/Firmware/src/lib/flight_tasks/tasks/Descend /home/arrow/Firmware/src/lib/flight_tasks/tasks/Transition /home/arrow/Firmware/src/lib/flight_tasks/tasks/Orbit /home/arrow/Firmware/src/lib/hysteresis /home/arrow/Firmware/src/lib/l1 /home/arrow/Firmware/src/lib/landing_slope /home/arrow/Firmware/src/lib/led /home/arrow/Firmware/src/lib/mag_compensation /home/arrow/Firmware/src/lib/mathlib /home/arrow/Firmware/src/lib/mixer_module /home/arrow/Firmware/src/lib/output_limit /home/arrow/Firmware/src/lib/pid /home/arrow/Firmware/src/lib/rc/rc_tests /home/arrow/Firmware/src/lib/systemlib /home/arrow/Firmware/src/lib/tecs /home/arrow/Firmware/src/lib/terrain_estimation /home/arrow/Firmware/src/lib/tunes /home/arrow/Firmware/src/lib/weather_vane /home/arrow/Firmware/platforms/posix/src/px4/common/px4_daemon /home/arrow/Firmware/platforms/posix/src/px4/common/lockstep_scheduler /home/arrow/Firmware/platforms/posix/src/px4/generic/generic/tone_alarm /home/arrow/Firmware/platforms/common/px4_work_queue /home/arrow/Firmware/platforms/common/px4_work_queue/test /home/arrow/Firmware/src/modules/uORB /home/arrow/Firmware/src/modules/uORB/uORB_tests /home/arrow/Firmware/src/drivers/camera_capture /home/arrow/Firmware/src/drivers/camera_trigger /home/arrow/Firmware/src/drivers/gps /home/arrow/Firmware/src/drivers/pwm_out_sim /home/arrow/Firmware/src/drivers/rpm/rpm_simulator /home/arrow/Firmware/src/drivers/tone_alarm /home/arrow/Firmware/src/modules/airship_att_control /home/arrow/Firmware/src/modules/airspeed_selector /home/arrow/Firmware/src/modules/attitude_estimator_q /home/arrow/Firmware/src/modules/camera_feedback /home/arrow/Firmware/src/modules/commander/failure_detector /home/arrow/Firmware/src/modules/commander/Arming/PreFlightCheck /home/arrow/Firmware/src/modules/commander/Arming/ArmAuthorization /home/arrow/Firmware/src/modules/commander/Arming/HealthFlags /home/arrow/Firmware/src/modules/commander /home/arrow/Firmware/src/modules/commander/commander_tests /home/arrow/Firmware/src/modules/dataman /home/arrow/Firmware/src/modules/ekf2/Utility /home/arrow/Firmware/src/modules/ekf2 /home/arrow/Firmware/src/modules/events /home/arrow/Firmware/src/modules/fw_att_control /home/arrow/Firmware/src/modules/fw_pos_control_l1/launchdetection /home/arrow/Firmware/src/modules/fw_pos_control_l1/runway_takeoff /home/arrow/Firmware/src/modules/fw_pos_control_l1 /home/arrow/Firmware/src/modules/land_detector /home/arrow/Firmware/src/modules/landing_target_estimator /home/arrow/Firmware/src/modules/local_position_estimator /home/arrow/Firmware/src/modules/logger /home/arrow/Firmware/src/modules/mavlink /home/arrow/Firmware/src/modules/mavlink/mavlink_tests /home/arrow/Firmware/src/modules/mc_att_control/AttitudeControl /home/arrow/Firmware/src/modules/mc_att_control /home/arrow/Firmware/src/modules/mc_hover_thrust_estimator /home/arrow/Firmware/src/modules/mc_pos_control/Takeoff /home/arrow/Firmware/src/modules/mc_pos_control/PositionControl /home/arrow/Firmware/src/modules/mc_pos_control /home/arrow/Firmware/src/modules/mc_rate_control/RateControl /home/arrow/Firmware/src/modules/mc_rate_control /home/arrow/Firmware/src/modules/navigator /home/arrow/Firmware/src/modules/rc_update /home/arrow/Firmware/src/modules/replay /home/arrow/Firmware/src/modules/rover_pos_control /home/arrow/Firmware/src/modules/sensors/data_validator /home/arrow/Firmware/src/modules/sensors/sensor_calibration /home/arrow/Firmware/src/modules/sensors/vehicle_acceleration /home/arrow/Firmware/src/modules/sensors/vehicle_angular_velocity /home/arrow/Firmware/src/modules/sensors/vehicle_air_data /home/arrow/Firmware/src/modules/sensors/vehicle_imu /home/arrow/Firmware/src/modules/sensors /home/arrow/Firmware/src/modules/simulator /home/arrow/Firmware/src/modules/simulator/battery_simulator /home/arrow/Firmware/src/modules/temperature_compensation /home/arrow/Firmware/src/modules/vmount /home/arrow/Firmware/src/modules/vtol_att_control /home/arrow/Firmware/src/modules/uuv_att_control /home/arrow/Firmware/src/systemcmds/dyn /home/arrow/Firmware/src/systemcmds/esc_calib /home/arrow/Firmware/src/systemcmds/led_control /home/arrow/Firmware/src/systemcmds/mixer /home/arrow/Firmware/src/systemcmds/motor_ramp /home/arrow/Firmware/src/systemcmds/motor_test /home/arrow/Firmware/src/systemcmds/param /home/arrow/Firmware/src/systemcmds/perf /home/arrow/Firmware/src/systemcmds/pwm /home/arrow/Firmware/src/systemcmds/sd_bench /home/arrow/Firmware/src/systemcmds/shutdown /home/arrow/Firmware/src/systemcmds/tests /home/arrow/Firmware/src/systemcmds/tests/hrt_test /home/arrow/Firmware/src/systemcmds/topic_listener /home/arrow/Firmware/src/systemcmds/tune_control /home/arrow/Firmware/src/systemcmds/ver /home/arrow/Firmware/src/systemcmds/work_queue /home/arrow/Firmware/src/examples/fake_magnetometer /home/arrow/Firmware/src/examples/fixedwing_control /home/arrow/Firmware/src/examples/hello /home/arrow/Firmware/src/examples/px4_mavlink_debug /home/arrow/Firmware/src/examples/px4_simple_app /home/arrow/Firmware/src/examples/rover_steering_control /home/arrow/Firmware/src/examples/uuv_example_app /home/arrow/Firmware/src/examples/work_item /home/arrow/Firmware/build/px4_sitl_default/generated_params --xml /home/arrow/Firmware/build/px4_sitl_default/parameters.xml --json /home/arrow/Firmware/build/px4_sitl_default/parameters.json --compress --inject-xml /home/arrow/Firmware/src/lib/parameters/parameters_injected.xml --overrides {} --board px4_sitl
Traceback (most recent call last):
  File "/home/arrow/Firmware/src/lib/parameters/px_process_params.py", line 192, in <module>
    main()
  File "/home/arrow/Firmware/src/lib/parameters/px_process_params.py", line 188, in main
    SaveCompressed(f)
  File "/home/arrow/Firmware/src/lib/parameters/px_process_params.py", line 62, in SaveCompressed
    f.write(content_file.read())
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2925: ordinal not in range(128)
[21/749] Generating uORB topic headers
FAILED: uORB/topics/uORBTopics.hpp uORB/topics/actuator_armed.h uORB/topics/actuator_controls.h uORB/topics/actuator_outputs.h uORB/topics/adc_report.h uORB/topics/airspeed.h uORB/topics/airspeed_validated.h uORB/topics/battery_status.h uORB/topics/camera_capture.h uORB/topics/camera_trigger.h uORB/topics/cellular_status.h uORB/topics/collision_constraints.h uORB/topics/collision_report.h uORB/topics/commander_state.h uORB/topics/cpuload.h uORB/topics/debug_array.h uORB/topics/debug_key_value.h uORB/topics/debug_value.h uORB/topics/debug_vect.h uORB/topics/differential_pressure.h uORB/topics/distance_sensor.h uORB/topics/ekf2_timestamps.h uORB/topics/ekf_gps_drift.h uORB/topics/ekf_gps_position.h uORB/topics/esc_report.h uORB/topics/esc_status.h uORB/topics/estimator_innovations.h uORB/topics/estimator_sensor_bias.h uORB/topics/estimator_status.h uORB/topics/follow_target.h uORB/topics/geofence_result.h uORB/topics/gps_dump.h uORB/topics/gps_inject_data.h uORB/topics/home_position.h uORB/topics/hover_thrust_estimate.h uORB/topics/input_rc.h uORB/topics/iridiumsbd_status.h uORB/topics/irlock_report.h uORB/topics/landing_gear.h uORB/topics/landing_target_innovations.h uORB/topics/landing_target_pose.h uORB/topics/led_control.h uORB/topics/log_message.h uORB/topics/logger_status.h uORB/topics/manual_control_setpoint.h uORB/topics/mavlink_log.h uORB/topics/mission.h uORB/topics/mission_result.h uORB/topics/mount_orientation.h uORB/topics/multirotor_motor_limits.h uORB/topics/obstacle_distance.h uORB/topics/offboard_control_mode.h uORB/topics/onboard_computer_status.h uORB/topics/optical_flow.h uORB/topics/orb_test.h uORB/topics/orb_test_large.h uORB/topics/orb_test_medium.h uORB/topics/orbit_status.h uORB/topics/parameter_update.h uORB/topics/ping.h uORB/topics/position_controller_landing_status.h uORB/topics/position_controller_status.h uORB/topics/position_setpoint.h uORB/topics/position_setpoint_triplet.h uORB/topics/power_button_state.h uORB/topics/power_monitor.h uORB/topics/pwm_input.h uORB/topics/px4io_status.h uORB/topics/qshell_req.h uORB/topics/qshell_retval.h uORB/topics/radio_status.h uORB/topics/rate_ctrl_status.h uORB/topics/rc_channels.h uORB/topics/rc_parameter_map.h uORB/topics/rpm.h uORB/topics/safety.h uORB/topics/satellite_info.h uORB/topics/sensor_accel.h uORB/topics/sensor_accel_fifo.h uORB/topics/sensor_baro.h uORB/topics/sensor_combined.h uORB/topics/sensor_correction.h uORB/topics/sensor_gyro.h uORB/topics/sensor_gyro_fifo.h uORB/topics/sensor_mag.h uORB/topics/sensor_preflight.h uORB/topics/sensor_selection.h uORB/topics/subsystem_info.h uORB/topics/system_power.h uORB/topics/task_stack_info.h uORB/topics/tecs_status.h uORB/topics/telemetry_heartbeat.h uORB/topics/telemetry_status.h uORB/topics/test_motor.h uORB/topics/timesync.h uORB/topics/timesync_status.h uORB/topics/trajectory_bezier.h uORB/topics/trajectory_waypoint.h uORB/topics/transponder_report.h uORB/topics/tune_control.h uORB/topics/uavcan_parameter_request.h uORB/topics/uavcan_parameter_value.h uORB/topics/ulog_stream.h uORB/topics/ulog_stream_ack.h uORB/topics/vehicle_acceleration.h uORB/topics/vehicle_air_data.h uORB/topics/vehicle_angular_acceleration.h uORB/topics/vehicle_angular_velocity.h uORB/topics/vehicle_attitude.h uORB/topics/vehicle_attitude_setpoint.h uORB/topics/vehicle_command.h uORB/topics/vehicle_command_ack.h uORB/topics/vehicle_constraints.h uORB/topics/vehicle_control_mode.h uORB/topics/vehicle_global_position.h uORB/topics/vehicle_gps_position.h uORB/topics/vehicle_imu.h uORB/topics/vehicle_imu_status.h uORB/topics/vehicle_land_detected.h uORB/topics/vehicle_local_position.h uORB/topics/vehicle_local_position_setpoint.h uORB/topics/vehicle_magnetometer.h uORB/topics/vehicle_odometry.h uORB/topics/vehicle_rates_setpoint.h uORB/topics/vehicle_roi.h uORB/topics/vehicle_status.h uORB/topics/vehicle_status_flags.h uORB/topics/vehicle_trajectory_bezier.h uORB/topics/vehicle_trajectory_waypoint.h uORB/topics/vtol_vehicle_status.h uORB/topics/wheel_encoders.h uORB/topics/wind_estimate.h uORB/topics/yaw_estimator_status.h 
cd /home/arrow/Firmware/msg && /usr/bin/python3 tools/px_generate_uorb_topic_files.py --headers -f actuator_armed.msg actuator_controls.msg actuator_outputs.msg adc_report.msg airspeed.msg airspeed_validated.msg battery_status.msg camera_capture.msg camera_trigger.msg cellular_status.msg collision_constraints.msg collision_report.msg commander_state.msg cpuload.msg debug_array.msg debug_key_value.msg debug_value.msg debug_vect.msg differential_pressure.msg distance_sensor.msg ekf2_timestamps.msg ekf_gps_drift.msg ekf_gps_position.msg esc_report.msg esc_status.msg estimator_innovations.msg estimator_sensor_bias.msg estimator_status.msg follow_target.msg geofence_result.msg gps_dump.msg gps_inject_data.msg home_position.msg hover_thrust_estimate.msg input_rc.msg iridiumsbd_status.msg irlock_report.msg landing_gear.msg landing_target_innovations.msg landing_target_pose.msg led_control.msg log_message.msg logger_status.msg manual_control_setpoint.msg mavlink_log.msg mission.msg mission_result.msg mount_orientation.msg multirotor_motor_limits.msg obstacle_distance.msg offboard_control_mode.msg onboard_computer_status.msg optical_flow.msg orb_test.msg orb_test_large.msg orb_test_medium.msg orbit_status.msg parameter_update.msg ping.msg position_controller_landing_status.msg position_controller_status.msg position_setpoint.msg position_setpoint_triplet.msg power_button_state.msg power_monitor.msg pwm_input.msg px4io_status.msg qshell_req.msg qshell_retval.msg radio_status.msg rate_ctrl_status.msg rc_channels.msg rc_parameter_map.msg rpm.msg safety.msg satellite_info.msg sensor_accel.msg sensor_accel_fifo.msg sensor_baro.msg sensor_combined.msg sensor_correction.msg sensor_gyro.msg sensor_gyro_fifo.msg sensor_mag.msg sensor_preflight.msg sensor_selection.msg subsystem_info.msg system_power.msg task_stack_info.msg tecs_status.msg telemetry_heartbeat.msg telemetry_status.msg test_motor.msg timesync.msg timesync_status.msg trajectory_bezier.msg trajectory_waypoint.msg transponder_report.msg tune_control.msg uavcan_parameter_request.msg uavcan_parameter_value.msg ulog_stream.msg ulog_stream_ack.msg vehicle_acceleration.msg vehicle_air_data.msg vehicle_angular_acceleration.msg vehicle_angular_velocity.msg vehicle_attitude.msg vehicle_attitude_setpoint.msg vehicle_command.msg vehicle_command_ack.msg vehicle_constraints.msg vehicle_control_mode.msg vehicle_global_position.msg vehicle_gps_position.msg vehicle_imu.msg vehicle_imu_status.msg vehicle_land_detected.msg vehicle_local_position.msg vehicle_local_position_setpoint.msg vehicle_magnetometer.msg vehicle_odometry.msg vehicle_rates_setpoint.msg vehicle_roi.msg vehicle_status.msg vehicle_status_flags.msg vehicle_trajectory_bezier.msg vehicle_trajectory_waypoint.msg vtol_vehicle_status.msg wheel_encoders.msg wind_estimate.msg yaw_estimator_status.msg -i /home/arrow/Firmware/msg -o /home/arrow/Firmware/build/px4_sitl_default/uORB/topics -e templates/uorb -t /home/arrow/Firmware/build/px4_sitl_default/msg/tmp/headers -q
Traceback (most recent call last):
  File "tools/px_generate_uorb_topic_files.py", line 530, in <module>
    generate_idx, f, args.temporarydir, args.package, args.templatedir, INCL_DEFAULT)
  File "tools/px_generate_uorb_topic_files.py", line 132, in generate_output_from_file
    msg_context, filename, full_type_name)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 285, in load_msg_from_file
    text = f.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3349: ordinal not in range(128)
ninja: build stopped: subcommand failed.
Makefile:224: recipe for target 'px4_sitl' failed
make: *** [px4_sitl] Error 1
```

**To Reproduce**
* clone the firmware
* checkout `v1.11.2`
* `git submodule update --recursive`
* `make px4_sitl gazebo`

@Jaeyoung-Lim any ideas?

**Comment by dagar** [comment]
Looks like python versioning.

**Comment by mzahana** [comment]
@dagar Same in master. I am using a docker container with Ubuntu 18 and ROS melodic

**Comment by mzahana** [comment]
@dagar If it compiles fine with you, could you mention the Python version you use?
For me, I am using Python 3.6.9

**Comment by Jaeyoung-Lim** [comment]
@mzahana We run build tests in the CI server using the containers https://github.com/PX4/PX4-containers, so it "should" work if everything is configured correctly

**Comment by mzahana** [comment]
Problem solved after using clean Ubuntu 18 environment.

**Comment by bigonestep** [comment]
Encountered the same problem, besides changing to a clean environment (although I am using a clean docker ubuntu18.04 environment with a desktop), what other solutions are there?

**Comment by mcelhennyi** [comment]
> Encountered the same problem, besides changing to a clean environment (although I am using a clean docker ubuntu18.04 environment with a desktop), what other solutions are there?

https://github.com/PX4/PX4-Autopilot/pull/13978#issuecomment-575884123

This helped me^^
