### ISSUE TITLE
Failed to import numpy

### ISSUE THREAD

**Issue by Yecgaa1** [PX4/PX4-Autopilot#17176]
Failed to import numpy in clion+0.9ToolChain

When I build px4 in Clion with cmake and cywin64
I see the problem

```
[  0%] Generating component_version.json
[  0%] Generating serial_params.c
Scanning dependencies of target drivers_board
[  1%] git submodule src/lib/ecl
[  1%] Generating uORB topic headers
[  1%] Generating mixer_multirotor_6dof.generated.h
[  1%] Generating mixer_multirotor.generated.h
[  1%] Generating mixer_multirotor_normalized.generated.h
[  2%] Generating ../../logs
[  2%] Generating git version header
[  2%] git submodule src/drivers/gps/devices
[  2%] git submodule mavlink/include/mavlink/v2.0
[  2%] Building CXX object boards/px4/sitl/src/CMakeFiles/drivers_board.dir/board_shutdown.cpp.o
Failed to import numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No such file or directory


You may need to install it using:
    pip3 install --user numpy

Failed to import numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No such file or directory


You may need to install it using:
    pip3 install --user numpy

Failed to import numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /usr/bin/python3),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No such file or directory


You may need to install it using:
    pip3 install --user numpy

make[3]: *** [src/lib/mixer/MultirotorMixer/CMakeFiles/mixer_gen.dir/build.make:130: src/lib/mixer/MultirotorMixer/mixer_multirotor_normalized.generated.h] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [src/lib/mixer/MultirotorMixer/CMakeFiles/mixer_gen.dir/build.make:104: src/lib/mixer/MultirotorMixer/mixer_multirotor.generated.h] Error 1
make[2]: *** [CMakeFiles/Makefile2:7531: src/lib/mixer/MultirotorMixer/CMakeFiles/mixer_gen.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: *** [src/lib/mixer/MultirotorMixer/CMakeFiles/mixer_gen_6dof.dir/build.make:103: src/lib/mixer/MultirotorMixer/mixer_multirotor_6dof.generated.h] Error 1
make[2]: *** [CMakeFiles/Makefile2:7504: src/lib/mixer/MultirotorMixer/CMakeFiles/mixer_gen_6dof.dir/all] Error 2
```
Ok,I know I should install numpy with run-console.bat
but it meet another wrong!

```
$ pip3 install --user pyserial empy toml numpy pandas jinja2 pyyaml pyros-genmsg packaging
Requirement already satisfied: pyserial in /usr/lib/python3.6/site-packages (3.4)
Requirement already satisfied: empy in /usr/lib/python3.6/site-packages (3.3.4)
Requirement already satisfied: toml in /usr/lib/python3.6/site-packages (0.10.0)
Requirement already satisfied: numpy in /usr/lib/python3.6/site-packages (1.16.2)
Collecting pandas
  Using cached https://files.pythonhosted.org/packages/fb/e4/828bb9c2474ff6016e5ce96a78220d485436d5468c23068f4f6c2eb9cff8/pandas-1.1.5.tar.gz
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.6 /usr/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-a41w3f3_/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.29.21,<3' 'numpy==1.15.4; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.15.4; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy; python_version>='"'"'3.9'"'"''
       cwd: None
  Complete output (355 lines):
  Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.9"' don't match your environment
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/0c/12/18eda60a1b961e0248e1b1e3ec1ff417420596dc7edf3614ef58a7a8cf6a/setuptools-54.1.2-py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
  Collecting Cython<3,>=0.29.21
    Using cached https://files.pythonhosted.org/packages/9e/98/bff39b3acaebbc6102be71797f655bbe60738f7339db4ad7bd0772c08daf/Cython-0.29.22-py2.py3-none-any.whl
  Collecting numpy==1.15.4
    Using cached https://files.pythonhosted.org/packages/2d/80/1809de155bad674b494248bcfca0e49eb4c5d8bee58f26fe7a0dd45029e2/numpy-1.15.4.zip
  Installing collected packages: setuptools, wheel, Cython, numpy
    Running setup.py install for numpy: started
      Running setup.py install for numpy: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7fcmp36h/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7fcmp36h/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-75szxg86/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-a41w3f3_/overlay --compile
           cwd: /tmp/pip-install-7fcmp36h/numpy/
      Complete output (330 lines):
      Running from numpy source directory.

      Note: if you need reliable uninstall behavior, then install
      with pip instead of using `setup.py install`:

        - `pip install .`       (from a git repo or downloaded source
                                 release)
        - `pip install numpy`   (last NumPy release on PyPi)


      blas_opt_info:
      blas_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      blis_info:
      customize UnixCCompiler
        libraries blis not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      openblas_info:
      customize UnixCCompiler
      customize UnixCCompiler
        libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries tatlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      atlas_3_10_blas_info:
      customize UnixCCompiler
        libraries satlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      atlas_blas_info:
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      accelerate_info:
        NOT AVAILABLE

      /tmp/pip-install-7fcmp36h/numpy/numpy/distutils/system_info.py:625: UserWarning:
          Atlas (http://math-atlas.sourceforge.net/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [atlas]) or by setting
          the ATLAS environment variable.
        self.calc_info()
      blas_info:
      customize UnixCCompiler
        libraries blas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      /tmp/pip-install-7fcmp36h/numpy/numpy/distutils/system_info.py:625: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        self.calc_info()
      blas_src_info:
        NOT AVAILABLE

      /tmp/pip-install-7fcmp36h/numpy/numpy/distutils/system_info.py:625: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        self.calc_info()
        NOT AVAILABLE

      /bin/sh: svnversion: 未找到命令
      non-existing path in 'numpy/distutils': 'site.cfg'
      /bin/sh: svnversion: 未找到命令
      F2PY Version 2
      lapack_opt_info:
      lapack_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      openblas_lapack_info:
      customize UnixCCompiler
      customize UnixCCompiler
        libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      openblas_clapack_info:
      customize UnixCCompiler
      customize UnixCCompiler
        libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries tatlas,tatlas not found in /usr/lib/
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE

      atlas_3_10_info:
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries satlas,satlas not found in /usr/lib/
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE

      atlas_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE

      atlas_info:
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/local/lib
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/lib
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in /usr/lib/
      customize UnixCCompiler
        libraries lapack_atlas not found in /usr/lib/
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE

      lapack_info:
      customize UnixCCompiler
        libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/']
        NOT AVAILABLE

      /tmp/pip-install-7fcmp36h/numpy/numpy/distutils/system_info.py:625: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        self.calc_info()
      lapack_src_info:
        NOT AVAILABLE

      /tmp/pip-install-7fcmp36h/numpy/numpy/distutils/system_info.py:625: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        self.calc_info()
        NOT AVAILABLE

      /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running install
      running build
      running config_cc
      unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      build_src
      building py_modules sources
      creating build
      creating build/src.cygwin-3.1.4-x86_64-3.6
      creating build/src.cygwin-3.1.4-x86_64-3.6/numpy
      creating build/src.cygwin-3.1.4-x86_64-3.6/numpy/distutils
      building library "npymath" sources
      get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95']'
      customize GnuFCompiler
      Could not locate executable g77
      Could not locate executable f77
      customize IntelVisualFCompiler
      Could not locate executable ifort
      Could not locate executable ifl
      customize AbsoftFCompiler
      Could not locate executable f90
      customize CompaqVisualFCompiler
      Found executable /usr/bin/DF
      customize IntelItaniumVisualFCompiler
      Could not locate executable efl
      customize Gnu95FCompiler
      Could not locate executable gfortran
      Could not locate executable f95
      customize G95FCompiler
      Could not locate executable g95
      don't know how to compile Fortran code on platform 'posix'
      C compiler: gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/usr/src/ports/python36/python36-3.6.9-1.x86_64/build=/usr/src/debug/python36-3.6.9-1 -fdebug-prefix-map=/usr/src/ports/python36/python36-3.6.9-1.x86_64/src/Python-3.6.9=/usr/src/debug/python36-3.6.9-1 -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/usr/src/ports/python36/python36-3.6.9-1.x86_64/build=/usr/src/debug/python36-3.6.9-1 -fdebug-prefix-map=/usr/src/ports/python36/python36-3.6.9-1.x86_64/src/Python-3.6.9=/usr/src/debug/python36-3.6.9-1

      compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.6m -c'
      gcc: _configtest.c
      gcc _configtest.o -o _configtest.exe
      success!
      removing: _configtest.c _configtest.o _configtest.o.d _configtest.exe
      C compiler: gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/usr/src/ports/python36/python36-3.6.9-1.x86_64/build=/usr/src/debug/python36-3.6.9-1 -fdebug-prefix-map=/usr/src/ports/python36/python36-3.6.9-1.x86_64/src/Python-3.6.9=/usr/src/debug/python36-3.6.9-1 -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/usr/src/ports/python36/python36-3.6.9-1.x86_64/build=/usr/src/debug/python36-3.6.9-1 -fdebug-prefix-map=/usr/src/ports/python36/python36-3.6.9-1.x86_64/src/Python-3.6.9=/usr/src/debug/python36-3.6.9-1

      compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.6m -c'
      gcc: _configtest.c
      _configtest.c:1:5: 警告：conflicting types for built-in function ‘exp’; expected ‘double(double)’ [-Wbuiltin-declaration-mismatch]
          1 | int exp (void);
            |     ^~~
      _configtest.c:1:1: 附注：‘exp’ is declared in header ‘<math.h>’
        +++ |+#include <math.h>
          1 | int exp (void);
      gcc _configtest.o -o _configtest.exe
      success!
      removing: _configtest.c _configtest.o _configtest.o.d _configtest.exe
      creating build/src.cygwin-3.1.4-x86_64-3.6/numpy/core
      creating build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src
      creating build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/npymath
      conv_template:> build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/npymath/npy_math_internal.h
        adding 'build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/npymath' to include_dirs.
      conv_template:> build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/npymath/ieee754.c
      conv_template:> build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/npymath/npy_math_complex.c
      None - nothing done with h_files = ['build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/npymath/npy_math_internal.h']
      building library "npysort" sources
      creating build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/npysort
      conv_template:> build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/npysort/quicksort.c
      conv_template:> build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/npysort/mergesort.c
      conv_template:> build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/npysort/heapsort.c
      creating build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/private
      conv_template:> build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/private/npy_partition.h
        adding 'build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/private' to include_dirs.
      conv_template:> build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/npysort/selection.c
      conv_template:> build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/private/npy_binsearch.h
      conv_template:> build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/npysort/binsearch.c
      None - nothing done with h_files = ['build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/private/npy_partition.h', 'build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/src/private/npy_binsearch.h']
      building extension "numpy.core._dummy" sources
      Generating build/src.cygwin-3.1.4-x86_64-3.6/numpy/core/include/numpy/config.h
      C compiler: gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/usr/src/ports/python36/python36-3.6.9-1.x86_64/build=/usr/src/debug/python36-3.6.9-1 -fdebug-prefix-map=/usr/src/ports/python36/python36-3.6.9-1.x86_64/src/Python-3.6.9=/usr/src/debug/python36-3.6.9-1 -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/usr/src/ports/python36/python36-3.6.9-1.x86_64/build=/usr/src/debug/python36-3.6.9-1 -fdebug-prefix-map=/usr/src/ports/python36/python36-3.6.9-1.x86_64/src/Python-3.6.9=/usr/src/debug/python36-3.6.9-1

      compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.6m -c'
      gcc: _configtest.c
      _configtest.c:1:10: 致命错误：Python.h：No such file or directory
          1 | #include <Python.h>
            |          ^~~~~~~~~~
      编译中断。
      _configtest.c:1:10: 致命错误：Python.h：No such file or directory
          1 | #include <Python.h>
            |          ^~~~~~~~~~
      编译中断。
      failure.
      removing: _configtest.c _configtest.o
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-7fcmp36h/numpy/setup.py", line 403, in <module>
          setup_package()
        File "/tmp/pip-install-7fcmp36h/numpy/setup.py", line 395, in setup_package
          setup(**metadata)
        File "/tmp/pip-install-7fcmp36h/numpy/numpy/distutils/core.py", line 169, in setup
          return old_setup(**new_attr)
        File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-7fcmp36h/numpy/numpy/distutils/command/install.py", line 62, in run
          r = self.setuptools_run()
        File "/tmp/pip-install-7fcmp36h/numpy/numpy/distutils/command/install.py", line 36, in setuptools_run
          return distutils_install.run(self)
        File "/usr/lib/python3.6/distutils/command/install.py", line 545, in run
          self.run_command('build')
        File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-7fcmp36h/numpy/numpy/distutils/command/build.py", line 47, in run
          old_build.run(self)
        File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-7fcmp36h/numpy/numpy/distutils/command/build_src.py", line 148, in run
          self.build_sources()
        File "/tmp/pip-install-7fcmp36h/numpy/numpy/distutils/command/build_src.py", line 165, in build_sources
          self.build_extension_sources(ext)
        File "/tmp/pip-install-7fcmp36h/numpy/numpy/distutils/command/build_src.py", line 324, in build_extension_sources
          sources = self.generate_sources(sources, ext)
        File "/tmp/pip-install-7fcmp36h/numpy/numpy/distutils/command/build_src.py", line 377, in generate_sources
          source = func(extension, build_dir)
        File "numpy/core/setup.py", line 422, in generate_config_h
          moredefs, ignored = cocache.check_types(config_cmd, ext, build_dir)
        File "numpy/core/setup.py", line 48, in check_types
          out = check_types(*a, **kw)
        File "numpy/core/setup.py", line 281, in check_types
          "install {0}-dev|{0}-devel.".format(python))
      SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7fcmp36h/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7fcmp36h/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-75szxg86/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-a41w3f3_/overlay --compile Check the logs for full command output.
  WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.6 /usr/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-a41w3f3_/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.29.21,<3' 'numpy==1.15.4; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.15.4; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version=='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy; python_version>='"'"'3.9'"'"'' Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Addition:
```
xtx@DESKTOP-65G5ROL ~
$ which python
/usr/local/bin/python

xtx@DESKTOP-65G5ROL ~
$ which python3
/usr/bin/python3

xtx@DESKTOP-65G5ROL ~
$ which pip
which: no pip in (/usr/local/bin:/usr/bin:/usr/bin:/cygdrive/d/PX4/toolchain/gcc-arm/bin:/cygdrive/d/PX4/toolchain/jdk/bin:/cygdrive/d/PX4/toolchain/apache-ant/bin:/cygdrive/d/PX4/toolchain/genromfs:/cygdrive/d/PX4/toolchain/misc:/usr/lib/lapack)

xtx@DESKTOP-65G5ROL ~
$ which pip3
/usr/bin/pip3

xtx@DESKTOP-65G5ROL ~
$ python --version
Python 3.6.9

xtx@DESKTOP-65G5ROL ~
$ python3 --version
Python 3.6.9

xtx@DESKTOP-65G5ROL ~
$ pip --version
bash: pip: 未找到命令

xtx@DESKTOP-65G5ROL ~
$ pip3 --version
pip 19.2.3 from /usr/lib/python3.6/site-packages/pip (python 3.6)
```

**Comment by adbidwai** [comment]
Install numpy for python2 and try again
```
sudo apt-get install python
sudo apt-get install python-numpy
```

**Comment by Yecgaa1** [comment]
> Install numpy for python2 and try again
> 
> ```
> sudo apt-get install python
> sudo apt-get install python-numpy
> ```

No!I run the toolChain in Win10
