### ISSUE TITLE
Failure while building ROS 2 Workspace in a docker container on Nvidia Jetson AGX Xavier

### ISSUE THREAD

**Issue by codingCoffee** [PX4/PX4-Autopilot#18328]
**Describe the bug**
1. I've been following [ROS 2 User Guide (PX4-ROS 2 Bridge)](http://docs.px4.io/master/en/ros/ros2_comm.html#build-ros-2-workspace) to setup ROS 2 with PX4 and the last step to build the ROS 2 workspace is failing, particularly the following command.
```
source build_ros2_workspace.bash
```
It fails and gives a non-zero exit code. Hence, it also closes the terminal. So I executed the same command as follows
```
bash build_ros2_workspace.bash --ros_distro foxy --ros_path /opt/ros/foxy/install/setup.bash --verbose
```

**To Reproduce**
Follow the official [ROS 2 User Guide (PX4-ROS 2 Bridge)](http://docs.px4.io/master/en/ros/ros2_comm.html#build-ros-2-workspace)

<details><summary>Click here to open the exact Dockerfile to reproduce the entire setup</summary>
<p>

```
#
# this dockerfile roughly follows the 'Install ROS From Source' procedures from:
#   https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Development-Setup/
#
ARG BASE_IMAGE=nvcr.io/nvidia/l4t-base:r32.5.0
FROM ${BASE_IMAGE}

ARG ROS_PKG=ros_base
ENV ROS_DISTRO=foxy
ENV ROS_ROOT=/opt/ros/${ROS_DISTRO}

ENV DEBIAN_FRONTEND=noninteractive
ENV SHELL /bin/bash
SHELL ["/bin/bash", "-c"]

WORKDIR /tmp

# change the locale from POSIX to UTF-8
RUN locale-gen en_US en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV PYTHONIOENCODING=utf-8


#
# add the ROS deb repo to the apt sources list
#
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
                curl \
                wget \
                gnupg2 \
                lsb-release \
                ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null


#
# install development packages
#
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
                build-essential \
                cmake \
                git \
                libbullet-dev \
                libpython3-dev \
                python3-colcon-common-extensions \
                python3-flake8 \
                python3-pip \
                python3-numpy \
                python3-pytest-cov \
                python3-rosdep \
                python3-setuptools \
                python3-vcstool \
                python3-rosinstall-generator \
                libasio-dev \
                libtinyxml2-dev \
                libcunit1-dev \
                libgazebo9-dev \
                gazebo9 \
                gazebo9-common \
                gazebo9-plugin-base \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# install some pip packages needed for testing
RUN python3 -m pip install -U \
                argcomplete \
                flake8-blind-except \
                flake8-builtins \
                flake8-class-newline \
                flake8-comprehensions \
                flake8-deprecated \
                flake8-docstrings \
                flake8-import-order \
                flake8-quotes \
                pytest-repeat \
                pytest-rerunfailures \
                pytest

#
# install OpenCV (with CUDA)
#
ARG OPENCV_URL=https://nvidia.box.com/shared/static/5v89u6g5rb62fpz4lh0rz531ajo2t5ef.gz
ARG OPENCV_DEB=OpenCV-4.5.0-aarch64.tar.gz

RUN apt-get purge -y '*opencv*' || echo "previous OpenCV installation not found" && \
    mkdir opencv && \
    cd opencv && \
    wget --quiet --show-progress --progress=bar:force:noscroll --no-check-certificate ${OPENCV_URL} -O ${OPENCV_DEB} && \
    tar -xzvf ${OPENCV_DEB} && \
    dpkg -i --force-depends *.deb && \
    apt-get update && \
    apt-get install -y -f --no-install-recommends && \
    dpkg -i *.deb && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean && \
    cd ../ && \
    rm -rf opencv && \
    cp -r /usr/include/opencv4 /usr/local/include/opencv4 && \
    cp -r /usr/lib/python3.6/dist-packages/cv2 /usr/local/lib/python3.6/dist-packages/cv2


#
# compile yaml-cpp-0.6, which some ROS packages may use (but is not in the 18.04 apt repo)
#
RUN git clone --branch yaml-cpp-0.6.0 https://github.com/jbeder/yaml-cpp yaml-cpp-0.6 && \
    cd yaml-cpp-0.6 && \
    mkdir build && \
    cd build && \
    cmake -DBUILD_SHARED_LIBS=ON .. && \
    make -j$(nproc) && \
    cp libyaml-cpp.so.0.6.0 /usr/lib/aarch64-linux-gnu/ && \
    ln -s /usr/lib/aarch64-linux-gnu/libyaml-cpp.so.0.6.0 /usr/lib/aarch64-linux-gnu/libyaml-cpp.so.0.6


#
# download/build ROS from source
#
RUN mkdir -p ${ROS_ROOT}/src && \
    cd ${ROS_ROOT} && \

    # https://answers.ros.org/question/325245/minimal-ros2-installation/?answer=325249#post-id-325249
    rosinstall_generator --deps --rosdistro ${ROS_DISTRO} ${ROS_PKG} \
                launch_xml \
                launch_yaml \
                launch_testing \
                launch_testing_ament_cmake \
                demo_nodes_cpp \
                demo_nodes_py \
                example_interfaces \
                camera_calibration_parsers \
                camera_info_manager \
                cv_bridge \
                v4l2_camera \
                vision_opencv \
                vision_msgs \
                image_geometry \
                image_pipeline \
                image_transport \
                compressed_image_transport \
                compressed_depth_image_transport \
                eigen3_cmake_module \
                > ros2.${ROS_DISTRO}.${ROS_PKG}.rosinstall && \
    cat ros2.${ROS_DISTRO}.${ROS_PKG}.rosinstall && \
    vcs import src < ros2.${ROS_DISTRO}.${ROS_PKG}.rosinstall && \

    # patch libyaml - https://github.com/dusty-nv/jetson-containers/issues/41#issuecomment-774767272
    rm ${ROS_ROOT}/src/libyaml_vendor/CMakeLists.txt && \
    wget --no-check-certificate https://raw.githubusercontent.com/ros2/libyaml_vendor/master/CMakeLists.txt -P ${ROS_ROOT}/src/libyaml_vendor/ && \

    # install dependencies using rosdep
    apt-get update && \
    cd ${ROS_ROOT} && \
    rosdep init && \
    rosdep update && \
    rosdep install -y \
          --ignore-src \
       --from-paths src \
          --rosdistro ${ROS_DISTRO} \
          --skip-keys "libopencv-dev libopencv-contrib-dev libopencv-imgproc-dev python-opencv python3-opencv" && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean && \

    # build it!
    colcon build --merge-install && \

    # remove build files
    rm -rf ${ROS_ROOT}/src && \
    rm -rf ${ROS_ROOT}/logs && \
    rm -rf ${ROS_ROOT}/build && \
    rm ${ROS_ROOT}/*.rosinstall


#
# fix broken package.xml in test_pluginlib that crops up if/when rosdep is run again
#
#   Error(s) in package '/opt/ros/foxy/build/pluginlib/prefix/share/test_pluginlib/package.xml':
#   Package 'test_pluginlib' must declare at least one maintainer
#   The package node must contain at least one "license" tag
#
#RUN TEST_PLUGINLIB_PACKAGE="${ROS_ROOT}/build/pluginlib/prefix/share/test_pluginlib/package.xml" && \
#    sed -i '/<\/description>/a <license>BSD<\/license>' $TEST_PLUGINLIB_PACKAGE && \
#    sed -i '/<\/description>/a <maintainer email="michael@openrobotics.org">Michael Carroll<\/maintainer>' $TEST_PLUGINLIB_PACKAGE && \
#    cat $TEST_PLUGINLIB_PACKAGE


#
# Set the default DDS middleware to cyclonedds
# https://github.com/ros2/rclcpp/issues/1335
#
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp


#
# setup entrypoint
#
COPY ./packages/ros_entrypoint.sh /ros_entrypoint.sh

RUN sed -i \
    's/ros_env_setup="\/opt\/ros\/$ROS_DISTRO\/setup.bash"/ros_env_setup="${ROS_ROOT}\/install\/setup.bash"/g' \
    /ros_entrypoint.sh && \
    cat /ros_entrypoint.sh

RUN echo 'source ${ROS_ROOT}/install/setup.bash' >> /root/.bashrc

ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
WORKDIR /

#https://ngc.nvidia.com/catalog/containers/nvidia:l4t-base
ARG L4T_MINOR_VERSION

#FROM nvcr.io/nvidia/l4t-base:r32.${L4T_MINOR_VERSION}

ARG L4T_MINOR_VERSION
ARG ZED_SDK_MAJOR
ARG ZED_SDK_MINOR
ARG JETPACK_MAJOR
ARG JETPACK_MINOR

#This environment variable is needed to use the streaming features on Jetson inside a container
ENV LOGNAME root
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -y && apt-get install --no-install-recommends lsb-release wget less udev sudo apt-transport-https build-essential cmake -y&& \
    echo "# R32 (release), REVISION: ${L4T_MINOR_VERSION}" > /etc/nv_tegra_release ; \
    wget -q --no-check-certificate -O ZED_SDK_Linux_JP.run https://download.stereolabs.com/zedsdk/${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}/jp${JETPACK_MAJOR}${JETPACK_MINOR}/jetsons && \
    chmod +x ZED_SDK_Linux_JP.run ; ./ZED_SDK_Linux_JP.run silent skip_tools && \
    rm -rf /usr/local/zed/resources/* \
    rm -rf ZED_SDK_Linux_JP.run && \
    rm -rf /var/lib/apt/lists/*

#This symbolic link is needed to use the streaming features on Jetson inside a container
RUN ln -sf /usr/lib/aarch64-linux-gnu/tegra/libv4l2.so.0 /usr/lib/aarch64-linux-gnu/libv4l2.so

WORKDIR /usr/local/zed

FROM codingcoffee/ros-zed:foxy-ros-base-l4t-r32.5.0-3.5-py-devel-jetson-jp4.5

RUN set -ex \
  && apt update \
  && apt install -y zip \
  && curl -s "https://get.sdkman.io" > /tmp/sdkman-install.sh \
  && bash /tmp/sdkman-install.sh \
  && source "$HOME/.sdkman/bin/sdkman-init.sh" \
  && sdk install gradle 6.3 \
  && cd ~ \
  && git clone https://github.com/eProsima/foonathan_memory_vendor.git --depth 1 \
  && cd foonathan_memory_vendor \
  && mkdir build \
  && cd build \
  && cmake .. \
  && cmake --build . --target install \
  && cd ~ \
  && git clone --recursive https://github.com/eProsima/Fast-DDS.git -b v2.0.2 ~/FastDDS-2.0.2 --depth 1 \
  && cd ~/FastDDS-2.0.2 \
  && mkdir build \
  && cd build  \
  && cmake -DTHIRDPARTY=ON -DSECURITY=ON .. \
  && make -j$(nproc --all) \
  && make install \
  && cd ~ \
  && git clone --recursive https://github.com/eProsima/Fast-DDS-Gen.git -b v1.0.4 ~/Fast-RTPS-Gen --depth 1 \
  && cd ~/Fast-RTPS-Gen \
  && gradle assemble \
  && env "PATH=$PATH" gradle install \
  && pip3 install -U empy pyros-genmsg setuptools \
  && cd ~ \
  && mkdir -p ~/px4_ros_com_ros2/src \
  && git clone https://github.com/PX4/px4_ros_com.git ~/px4_ros_com_ros2/src/px4_ros_com --depth 1 \
  && git clone https://github.com/PX4/px4_msgs.git ~/px4_ros_com_ros2/src/px4_msgs --depth 1
```

Command to build the container
```
docker build --build-arg L4T_MINOR_VERSION=5.0 --build-arg ZED_SDK_MAJOR=3 --build-arg ZED_SDK_MINOR=5 --build-arg JETPACK_MAJOR=4 --build-arg JETPACK_MINOR=5 -t ros-zed-mavlink .
```

Finally run the container and execute the following commands

```
cd ~/px4_ros_com_ros2/src/px4_ros_com/scripts
source build_ros2_workspace.bash --ros_distro foxy --ros_path /opt/ros/foxy/install/setup.bash
```

</p>
</details>

**Expected behavior**
I expected an exit code of 0. However, the shell gives a non zero exit code of `2` which also kills the terminal.

**Log Files and Screenshots**
```
-- Up-to-date: /root/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/cmake/px4_msgs__rosidl_typesupport_cppExport.cmake
-- Up-to-date: /root/px4_ros_com_ros2/install/px4_msgs/share/px4_msgs/cmake/px4_msgs__rosidl_typesupport_cppExport-relwithdebinfo.cmake
[Processing: px4_msgs]
Finished <<< px4_msgs [36.4s]
Starting >>> px4_ros_com
[  1%] Generating micro-RTPS agent code...
[  3%] Built target frame_transforms
[  5%] Built target debug_vect_advertiser
[  7%] Built target vehicle_gps_position_listener
[ 10%] Built target offboard_control
[ 11%] Built target sensor_combined_listener
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode)
Traceback (most recent call last):
  File "/root/px4_ros_com_ros2/src/px4_ros_com/scripts/generate_microRTPS_bridge.py", line 211, in <module>
    "dpkg -s ros-" + ros2_distro + "-fastrtps 2>/dev/null | grep -i version", shell=True).decode("utf-8").strip()).group(1)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'dpkg -s ros-foxy-fastrtps 2>/dev/null | grep -i version' returned non-zero exit status 1.
[ 11%] Generating micro-RTPS agent code...
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode)
Traceback (most recent call last):
  File "/root/px4_ros_com_ros2/src/px4_ros_com/scripts/generate_microRTPS_bridge.py", line 211, in <module>
    "dpkg -s ros-" + ros2_distro + "-fastrtps 2>/dev/null | grep -i version", shell=True).decode("utf-8").strip()).group(1)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'dpkg -s ros-foxy-fastrtps 2>/dev/null | grep -i version' returned non-zero exit status 1.
[ 12%] Building CXX object CMakeFiles/micrortps_agent.dir/src/micrortps_agent/microRTPS_agent.cpp.o
c++: error: /root/px4_ros_com_ros2/build/px4_ros_com/src/micrortps_agent/microRTPS_agent.cpp: No such file or directory
c++: fatal error: no input files
compilation terminated.
make[2]: *** [CMakeFiles/micrortps_agent.dir/src/micrortps_agent/microRTPS_agent.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/micrortps_agent.dir/build.make:496: recipe for target 'CMakeFiles/micrortps_agent.dir/src/micrortps_agent/microRTPS_agent.cpp.o' failed
CMakeFiles/Makefile2:173: recipe for target 'CMakeFiles/micrortps_agent.dir/all' failed
make[1]: *** [CMakeFiles/micrortps_agent.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
--- stderr: px4_ros_com
c++: error: /root/px4_ros_com_ros2/build/px4_ros_com/src/micrortps_agent/microRTPS_agent.cpp: No such file or directory
c++: fatal error: no input files
compilation terminated.
make[2]: *** [CMakeFiles/micrortps_agent.dir/src/micrortps_agent/microRTPS_agent.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/micrortps_agent.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< px4_ros_com [4.05s, exited with code 2]

Summary: 1 package finished [41.2s]
  1 package failed: px4_ros_com
  1 package had stderr output: px4_ros_com
```

**Additional context**
I've been executing all the steps inside a docker container on an Nvidia Jetson AGX Xavier, which is an ARM processor.

**Comment by Li-Jinjie** [comment]
I meet the same failure when building ROS 2 Workspace in a docker container on Nvidia Jetson TX2 NX

**Comment by Li-Jinjie** [comment]
Hello, I find a solution.
Just install python3-genmsg by inputing 
`apt-get install python3-genmsg`
This works for me.

Besides, I upload my docker image to docker hub: https://hub.docker.com/r/lijinjie/px4-ros2-arm64 , which is verified on TX2 NX.

I hope this method can solve your problem :)

**Comment by Ray0117** [comment]
Hi, I think it may be too late to tell the solution. But it may be helpful for the other users.

Actually, the official ROS2 user guide by PX4 is not compatible with Docker users. I found the method below, which can easily solve the compile error of px4_ros_com in ROS2 docker.

`mkdir -p ~/px4_ros_com_ros2/src`
`git clone https://github.com/PX4/px4_ros_com.git ~/px4_ros_com_ros2/src/px4_ros_com`
`git clone https://github.com/PX4/px4_msgs.git ~/px4_ros_com_ros2/src/px4_msgs`
**DIFFERENT BUT USEFUL STEPS**
`cd ~/px4_ros_com_ros2/src`
`source /opt/ros/foxy/setup.bash`
`colcon build`
`source install/setup.bash`

Then, everything will be done. You can `cd` to the PX4 code folder and compile what you want.
