### ISSUE TITLE
drivers/px4io cpu usage problem after running for long periods

### ISSUE THREAD

**Issue by dagar** [PX4/PX4-Autopilot#18375]
I just noticed this on the bench after leaving a vehicle running for several hours. It's repeatable.

![Screenshot from 2021-10-06 14-50-59](https://user-images.githubusercontent.com/84712/136265027-b2304479-b223-4ded-bc7a-09f12376927e.png)

![Screenshot from 2021-10-06 14-51-46](https://user-images.githubusercontent.com/84712/136265106-895b7d08-a73d-4469-a4fb-cfbdee7e0c92.png)

FYI @davids5 @bkueng

**Comment by dagar** [comment]
> It's hanging in https://github.com/PX4/NuttX/blob/px4_firmware_nuttx-10.1.0%2B/arch/arm/src/stm32f7/stm32_dma.c#L608
> 
> ```
> #0  dmast_getreg (offset=0, dmast=0x20020928 <g_dma+216>) at chip/stm32_dma.c:223
> #1  stm32_dmasetup (handle=0x20020928 <g_dma+216>, paddr=paddr@entry=1073773604, maddr=537032416, ntransfers=ntransfers@entry=68, scr=scr@entry=1280) at chip/stm32_dma.c:608
> #2  0x08117dae in ArchPX4IOSerial::_bus_exchange (this=0x2001f690, _packet=<optimized out>) at ../../platforms/nuttx/src/px4/stm/stm32f7/px4io_serial/px4io_serial.cpp:273
> #3  0x080547e2 in PX4IO_serial::write (this=0x2001f690, address=<optimized out>, data=0x20032534, count=8) at ../../src/drivers/px4io/px4io_serial.cpp:126
> #4  0x08051f98 in PX4IO::io_reg_set (this=this@entry=0x20032320, page=page@entry=54 '6', offset=<optimized out>, values=values@entry=0x20032534, num_values=num_values@entry=8) at ../../src/drivers/px4io/px4io.cpp:1383
> #5  0x08051fde in PX4IO::updateOutputs (this=0x20032320, stop_motors=<optimized out>, outputs=0x20032534, num_outputs=8, num_control_groups_updated=1) at ../../src/drivers/px4io/px4io.cpp:435
> #6  0x0811c0f6 in MixingOutput::updateStaticMixer (this=0x20032480) at ../../src/lib/mixer_module/mixer_module.cpp:738
> #7  0x0811c30a in MixingOutput::update (this=this@entry=0x20032480) at ../../src/lib/mixer_module/mixer_module.cpp:635
> #8  0x08053bb8 in PX4IO::Run (this=0x20032320) at ../../src/drivers/px4io/px4io.cpp:590
> ```

I take it you're still able to reproduce? I actually haven't seen it recently and I've been leaving a full px4_fmu-v5 setup running overnight.

**Comment by dagar** [comment]
Another instance of this bug. https://github.com/PX4/PX4-Autopilot/issues/18856
