### ISSUE TITLE
Crazyflie 2.0 and 2.1 cannot connect to nuttshell via USB

### ISSUE THREAD

**Issue by KaranJain21** [PX4/PX4-Autopilot#18524]
**Describe the bug**
Unable to connect to the nsh console of crazyflie 2.0 AND 2.1. This was working until commit [5eddf32cd38f25e385a1a171319e4e08a3a4a4dc](https://github.com/PX4/PX4-Autopilot/commit/5eddf32cd38f25e385a1a171319e4e08a3a4a4dc) (dated 2021-09-06) so issue probably arises due to some code pushed after that.
I am using Python 3.6.

**To Reproduce**
1. Compile the default PX4 firmware for the crazyflie 2.0 (or 2.1) using `make bitcraze_crazyflie_default upload` (or `make bitcraze_crazyflie21_default upload`)
2. Connect your computer to the vehicle via a USB port and flash the vehicle.
3. Try to connect to the nsh console using the command `./Tools/mavlink_shell.py` (should auto-detect the port) or using the port ID via `./Tools/mavlink_shell.py /dev/ttyACM0`
4. The firmware does not connect to nuttshell because the USB connection is not recognized (see error logs attached below).

**Expected behavior**
The connection succeeds and the console displays _nsh>_

**Error Log**
On using `./Tools/mavlink_shell.py`
```
Auto-detected serial ports are:
 /dev/ttyS31
 /dev/ttyS30
 /dev/ttyS29
 /dev/ttyS28
 /dev/ttyS27
 /dev/ttyS26
 /dev/ttyS25
 /dev/ttyS24
 /dev/ttyS23
 /dev/ttyS22
 /dev/ttyS21
 /dev/ttyS20
 /dev/ttyS19
 /dev/ttyS18
 /dev/ttyS17
 /dev/ttyS16
 /dev/ttyS15
 /dev/ttyS14
 /dev/ttyS13
 /dev/ttyS12
 /dev/ttyS11
 /dev/ttyS10
 /dev/ttyS9
 /dev/ttyS8
 /dev/ttyS7
 /dev/ttyS6
 /dev/ttyS5
 /dev/ttyS4
 /dev/ttyS3
 /dev/ttyS2
 /dev/ttyS1
 /dev/ttyS0
Using port /dev/ttyS31
Connecting to MAVLINK...
Traceback (most recent call last):
  File "~/.local/lib/python3.6/site-packages/serial/serialposix.py", line 398, in _reconfigure_port
    orig_attr = termios.tcgetattr(self.fd)
termios.error: (5, 'Input/output error')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Tools/mavlink_shell.py", line 245, in <module>
    main()
  File "./Tools/mavlink_shell.py", line 136, in main
    mav_serialport = MavlinkSerialPort(args.port, args.baudrate, devnum=10)
  File "./Tools/mavlink_shell.py", line 47, in __init__
    self.mav = mavutil.mavlink_connection(portname, autoreconnect=True, baud=baudrate)
  File "~/.local/lib/python3.6/site-packages/pymavlink/mavutil.py", line 1735, in mavlink_connection
    force_connected=force_connected)
  File "~/.local/lib/python3.6/site-packages/pymavlink/mavutil.py", line 926, in __init__
    raise e
  File "~/.local/lib/python3.6/site-packages/pymavlink/mavutil.py", line 923, in __init__
    dsrdtr=False, rtscts=False, xonxoff=False)
  File "~/.local/lib/python3.6/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "~/.local/lib/python3.6/site-packages/serial/serialposix.py", line 332, in open
    self._reconfigure_port(force_update=True)
  File "~/.local/lib/python3.6/site-packages/serial/serialposix.py", line 401, in _reconfigure_port
    raise SerialException("Could not configure port: {}".format(msg))
serial.serialutil.SerialException: Could not configure port: (5, 'Input/output error')
```

and on using the specific port that usually connects (with the commit ID linked above) `./Tools/mavlink_shell.py /dev/ttyACM0`
```
Connecting to MAVLINK...
Traceback (most recent call last):
  File "~/.local/lib/python3.6/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Tools/mavlink_shell.py", line 245, in <module>
    main()
  File "./Tools/mavlink_shell.py", line 136, in main
    mav_serialport = MavlinkSerialPort(args.port, args.baudrate, devnum=10)
  File "./Tools/mavlink_shell.py", line 47, in __init__
    self.mav = mavutil.mavlink_connection(portname, autoreconnect=True, baud=baudrate)
  File "~/.local/lib/python3.6/site-packages/pymavlink/mavutil.py", line 1735, in mavlink_connection
    force_connected=force_connected)
  File "~/.local/lib/python3.6/site-packages/pymavlink/mavutil.py", line 926, in __init__
    raise e
  File "~/.local/lib/python3.6/site-packages/pymavlink/mavutil.py", line 923, in __init__
    dsrdtr=False, rtscts=False, xonxoff=False)
  File "~/.local/lib/python3.6/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "~/.local/lib/python3.6/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
```

**Comment by hamishwillee** [comment]
Closing - more than just a little stale. If this is still a problem, please replicate on current main or stable and repost.
