### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: - make px4_sitl jmavsim fail on Mac OS

### ISSUE THREAD

**Issue by ganesh-androidev** [PX4/PX4-Autopilot#18743]
**Describe the bug**
 Exception in thread "main" java.lang.UnsupportedClassVersionError:

make px4_sitl jmavsim fail on Mac OS. Emulator not able to launch on MAC PC.

**To Reproduce**
Run : 

Followed below Terminal Commands:

brew tap PX4/px4
brew install px4-dev
pip3 install --user pyserial empy toml numpy pandas jinja2 pyyaml pyros-genmsg packaging
brew tap AdoptOpenJDK/openjdk
brew cask install adoptopenjdk14
brew install px4-sim-jmavsim
cd developer
git clone https://github.com/PX4/Firmware.git --recursive
cd Firmware
make px4_sitl jmavsim

**Expected behavior**
Launch Simulator

**Log Files and Screenshots**
*Always* 

BUILD SUCCESSFUL
Total time: 3 seconds
Exception in thread "main" java.lang.UnsupportedClassVersionError: me/drton/jmavsim/Simulator has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at **org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:59)**

Add screenshots to help explain your problem.

**Drone (please complete the following information):**
- Describe the type of drone.
- Photo of the IMU / autopilot setup if possible.

**Additional context**

**Comment by ChoudharyRamesh** [comment]
I ran into the same problem when i was changed java version to 8. 
Steps to solve this problem :-
1. Download java SE JDK 16 or above 
2. set JAVA_HOME="/jdk-install-path/Content/Home" in .zshrc file.

**Comment by hamishwillee** [comment]
Looks solved.
