### ISSUE TITLE
[Bug] [sitl_0-2] process has died 

### ISSUE THREAD

**Issue by AllenHuangDongyue** [PX4/PX4-Autopilot#21911]
### Describe the bug

Following the instruction to use SITL by roslaunch px4 posix_sitl.launch.

It shows [sitl_0-2] process has died ....

### To Reproduce
Ubuntu 20.04

git clone git@github.com:PX4/PX4-Autopilot.git
git submodule update --init --recursive
make px4_sitl_default gazebo (works)
roslaunch px4 posix_sitl.launch 

### Expected behavior

it should work without an error

**What is more, it can work under v1.13.3.**

### Flight Log

REQUIRED process [sitl-2] has died!
process has died [pid 182662, exit code 255, cmd /home/allen/Documents/PX4-Autopilot/build/px4_sitl_default/bin/px4 /home/allen/Documents/PX4-Autopilot/build/px4_sitl_default/etc -s etc/init.d-posix/rcS __name:=sitl __log:=/home/allen/.ros/log/0f2aca38-2f7c-11ee-8a38-55eff32c2a31/sitl-2.log].
log file: /home/allen/.ros/log/0f2aca38-2f7c-11ee-8a38-55eff32c2a31/sitl-2*.log
Initiating shutdown!

[vehicle_spawn_allen_182637_4391226950032247362-5] killing on exit
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/gazebo_ros/spawn_model", line 20, in <module>
    import rospy
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 64, in <module>
[gazebo_gui-4] killing on exit
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
[gazebo-3] killing on exit
[sitl-2] killing on exit
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.8/site.py", line 79, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 100, in <module>
    import os
  File "/usr/lib/python3.8/os.py", line 29, in <module>
    from . import _internal
  File "/usr/lib/python3/dist-packages/numpy/core/_internal.py", line 11, in <module>
    from _collections_abc import _check_methods
  File "/usr/lib/python3.8/_collections_abc.py", line 923, in <module>
    import platform
  File "/usr/lib/python3.8/platform.py", line 742, in <module>
    class ByteString(Sequence):
  File "/usr/lib/python3.8/abc.py", line 85, in __new__
    uname_result = collections.namedtuple("uname_result",
  File "/usr/lib/python3.8/collections/__init__.py", line 394, in namedtuple
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
KeyboardInterrupt
    exec(s, namespace)
  File "<string>", line 1, in <module>
KeyboardInterrupt

### Software Version

v1.14.0-beta2-452-g95b3005679

### Flight controller

v1.14.0-beta2-452-g95b3005679

### Vehicle type

Multicopter

**Comment by AllenHuangDongyue** [comment]
I also source the path by 
"source Tools/simulation/gazebo-classic/setup_gazebo.bash $(pwd) $(pwd)/build/px4_sitl_default
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)/Tools/simulation/gazebo-classic/sitl_gazebo-classic"

**Comment by AllenHuangDongyue** [comment]
Found the solutions, if someone faces a similar problem, you'd better check your ros enviroument.

**Comment by rvannamen** [comment]
@AllenHuangDongyue I am facing the same problem. Could please give some more information about what was wrong with your ROS environment?

**Comment by AllenHuangDongyue** [comment]
> @AllenHuangDongyue I am facing the same problem. Could please give some more information about what was wrong with your ROS environment?

@rvannamen I just reinstalled all the ros dependencies, maybe you can try it as well? Hope it will help.

**Comment by JohnTGZ** [comment]
@AllenHuangDongyue Can you elaborate on what ROS dependencies did you re-install?

**Comment by AllenHuangDongyue** [comment]
> @AllenHuangDongyue Can you elaborate on what ROS dependencies did you re-install?

Hi, John, I am not sure which specific one I install, I just re-installed all of them.
